CLOUD-651 fix: smartupdate starts after pod deletion
percona/percona-xtradb-cluster-operator pull request #1040
Opened 2021-11-05 11:09 UTC by pooknull

https://jira.percona.com/browse/CLOUD-651

Fix statefulSet change detection logic

2021-11-05 14:20 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| scheduled-backup | passed |
| recreate | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| big-data | passed |
| storage | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| security-context | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1040/commits/aed10cb0dfd4a75fbb6dbf370d21e78c8f8d3dc3
image: `perconalab/percona-xtradb-cluster-operator:PR-1040-aed10cb0`

2021-11-05 22:39 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| big-data | passed |
| haproxy | passed |
| restore-to-encrypted-cluster | passed |
| init-deploy | passed |
| demand-backup | passed |
| limits | passed |
| pitr | passed |
| monitoring-2-0 | passed |
| demand-backup-encrypted-with-tls | passed |
| affinity | passed |
| scaling | passed |
| storage | passed |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| one-pod | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| auto-tuning | passed |
| security-context | passed |
| self-healing-chaos | passed |
| proxysql-sidecar-res-limits | passed |
| self-healing-advanced | passed |
| users | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1040/commits/aed10cb0dfd4a75fbb6dbf370d21e78c8f8d3dc3
image: `perconalab/percona-xtradb-cluster-operator:PR-1040-aed10cb0`

2021-11-08 06:22 UTC, egegunes approved these changes

2021-11-08 06:39 UTC, delgod requested changes

2021-11-08 06:39 UTC, delgod commented on pkg/controller/pxc/upgrade.go
> +		if pod.ObjectMeta.Labels["controller-revision-hash"] != currentSet.Status.UpdateRevision {
what if the Operator pod was killed in the middle of SmartUpdate.
will Operator continue the SmartUpdate of will be stuck?

2021-11-08 14:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/percona/percona-xtradb-cluster-operator?pullRequest=1040) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/percona/percona-xtradb-cluster-operator?pullRequest=1040) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/percona/percona-xtradb-cluster-operator?pullRequest=1040) it.</sub>

2021-11-08 15:30 UTC, delgod requested changes

2021-11-08 15:30 UTC, delgod commented on pkg/controller/pxc/upgrade.go
> +	update := false
can we please rename var? for better code reading
```suggestion
	updateInProgress := false
```

2021-11-08 16:08 UTC, delgod approved these changes

2021-11-08 19:47 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| storage | passed |
| recreate | passed |
| haproxy | passed |
| scaling | passed |
| big-data | failed |
| self-healing | passed |
| self-healing-chaos | failed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| demand-backup | passed |
| smart-update | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| pitr | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1040/commits/399ac8e0a58bdeabd08706d9dea6976a8853a0b8
image: `perconalab/percona-xtradb-cluster-operator:PR-1040-399ac8e0`

2021-11-09 06:26 UTC, egegunes approved these changes

2021-11-09 07:53 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| upgrade-haproxy | passed |
| storage | passed |
| proxysql-sidecar-res-limits | passed |
| scaling | passed |
| recreate | passed |
| self-healing | passed |
| users | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| self-healing-chaos | passed |
| tls-issue-self | passed |
| security-context | passed |
| demand-backup | passed |
| tls-issue-cert-manager | passed |
| big-data | passed |
| pitr | passed |
| scheduled-backup | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1040/commits/399ac8e0a58bdeabd08706d9dea6976a8853a0b8
image: `perconalab/percona-xtradb-cluster-operator:PR-1040-399ac8e0`

2021-11-09 09:38 UTC, merged