Update README.md - quick fix
percona/percona-xtradb-cluster-operator pull request #1097
Opened 2022-02-01 15:47 UTC by spron-in

Correct the naming
Add help
Simplify quick installation

2022-02-01 15:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/percona/percona-xtradb-cluster-operator?pullRequest=1097) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/percona/percona-xtradb-cluster-operator?pullRequest=1097) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/percona/percona-xtradb-cluster-operator?pullRequest=1097) it.</sub>

2022-02-01 19:07 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| storage | passed |
| big-data | passed |
| haproxy | passed |
| scheduled-backup | passed |
| scaling | passed |
| recreate | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| upgrade-consistency | passed |
| users | failed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1097/commits/089ec4a2efcdbf1d12d9113c94274bb26a31dd8d
image: `perconalab/percona-xtradb-cluster-operator:PR-1097-089ec4a2`

2022-02-02 11:28 UTC, fiowro approved these changes

2022-02-02 14:38 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| big-data | passed |
| scaling | passed |
| recreate | passed |
| haproxy | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| upgrade-consistency | passed |
| users | passed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1097/commits/b1dba85e328ef78ea6b7f52785b4a10a8e33e427
image: `perconalab/percona-xtradb-cluster-operator:PR-1097-b1dba85e`

2022-02-02 14:38 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| big-data | passed |
| haproxy | passed |
| scaling | passed |
| scheduled-backup | passed |
| storage | passed |
| recreate | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| affinity | passed |
| one-pod | passed |
| pitr | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| upgrade-consistency | failed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1097/commits/d1c941f40e973fa039da72c0989428dd2b9eb23f
image: `perconalab/percona-xtradb-cluster-operator:PR-1097-d1c941f4`

2022-02-02 14:44 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| storage | passed |
| big-data | passed |
| scaling | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| init-deploy | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| limits | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| upgrade-consistency | failed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1097/commits/2ad191539e577fa038c09336469da5762a0c07e3
image: `perconalab/percona-xtradb-cluster-operator:PR-1097-2ad19153`

2022-02-22 12:16 UTC, hors requested changes

2022-02-22 12:16 UTC, hors commented on README.md
> +Deploy the database cluster itself from `deploy/cr.yaml`:
`deploy/cr.yaml or deploy/cr-minimal.yaml `?

2022-03-01 08:42 UTC, spron-in commented on README.md
> +Deploy the database cluster itself from `deploy/cr.yaml`:
Let's leave cr.yaml here.

2022-03-01 08:43 UTC, fiowro approved these changes

2022-03-01 18:44 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| recreate | failed |
| haproxy | failed |
| big-data | failed |
| scaling | failed |
| upgrade-haproxy | failed |
| storage | failed |
| scheduled-backup | failed |
| restore-to-encrypted-cluster | failed |
| init-deploy | failed |
| scaling-proxysql | failed |
| self-healing | passed |
| self-healing-chaos | failed |
| upgrade-proxysql | failed |
| demand-backup | failed |
| limits | failed |
| security-context | failed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| smart-update | failed |
| pitr | failed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| upgrade-consistency | failed |
| affinity | failed |
| demand-backup-encrypted-with-tls | failed |
| one-pod | failed |
| auto-tuning | failed |
| proxysql-sidecar-res-limits | failed |
| users | failed |
| tls-issue-self | failed |
| tls-issue-cert-manager | failed |
| tls-issue-cert-manager-ref | failed |
| validation-hook | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1097/commits/094c290ebac51dc0c6ba1dc3320e2dac53eaeda9
image: `perconalab/percona-xtradb-cluster-operator:PR-1097-094c290e`

2022-03-08 13:59 UTC, hors approved these changes

2022-03-08 14:01 UTC, merged