K8SPXC-341 : haproxy tests
percona/percona-xtradb-cluster-operator pull request #525
Opened 2020-08-03 16:07 UTC by AlyHKafoury

2020-08-03 18:18 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| scaling | passed |
| init-deploy | passed |
| big-data | passed |
| storage | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | failed |
| upgrade | passed |
| limits | passed |
| demand-backup | passed |
| self-healing-advanced | passed |
| monitoring | failed |
| upgrade-consistency | failed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| security-context | passed |
| affinity | passed |
| scheduled-backup | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | failed |

2020-08-05 07:34 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| big-data | passed |
| self-healing | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring | passed |
| operator-self-healing | passed |
| recreate | passed |
| restore-to-encrypted-cluster | failed |
| scaling | passed |
| scaling-proxysql | passed |
| upgrade | passed |
| upgrade-consistency | failed |
| security-context | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | failed |

2020-08-11 22:07 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | failed |
| recreate | passed |
| big-data | passed |
| scaling | passed |
| limits | passed |
| self-healing | failed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | failed |
| upgrade | failed |
| demand-backup | passed |
| self-healing-advanced | passed |
| monitoring | passed |
| upgrade-consistency | failed |
| operator-self-healing | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| scheduled-backup | failed |
| affinity | passed |
| one-pod | passed |
| demand-backup-encrypted-with-tls | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |

2020-08-12 22:37 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| big-data | passed |
| recreate | failed |
| scaling | passed |
| restore-to-encrypted-cluster | failed |
| self-healing | failed |
| scaling-proxysql | passed |
| limits | passed |
| demand-backup | passed |
| monitoring | passed |
| upgrade | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| upgrade-consistency | failed |
| monitoring-2-0 | passed |
| security-context | passed |
| scheduled-backup | failed |
| affinity | passed |
| demand-backup-encrypted-with-tls | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |

2020-08-13 17:05 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| storage | passed |
| self-healing | failed |
| scaling-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| restore-to-encrypted-cluster | failed |
| upgrade | passed |
| monitoring | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| monitoring-2-0 | passed |
| upgrade-consistency | failed |
| security-context | passed |
| affinity | passed |
| one-pod | passed |
| scheduled-backup | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | failed |

2020-08-17 13:12 UTC, cap1984 commented
Please add test to Jenkinsfile

2020-08-18 17:13 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| scaling | passed |
| big-data | passed |
| recreate | passed |
| self-healing | failed |
| limits | passed |
| scaling-proxysql | passed |
| monitoring | passed |
| self-healing-advanced | passed |
| upgrade | passed |
| restore-to-encrypted-cluster | failed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| upgrade-consistency | failed |
| operator-self-healing | passed |
| security-context | passed |
| affinity | passed |
| one-pod | passed |
| scheduled-backup | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| haproxy | passed |
| demand-backup-encrypted-with-tls | failed |

2020-08-18 23:23 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| recreate | passed |
| storage | passed |
| big-data | passed |
| scaling | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| limits | passed |
| restore-to-encrypted-cluster | failed |
| upgrade | passed |
| self-healing-advanced | passed |
| monitoring | failed |
| upgrade-consistency | passed |
| demand-backup | failed |
| security-context | passed |
| monitoring-2-0 | failed |
| affinity | passed |
| scheduled-backup | failed |
| operator-self-healing | passed |
| one-pod | passed |
| auto-tuning | passed |
| demand-backup-encrypted-with-tls | failed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| haproxy | failed |

2020-08-19 11:31 UTC, hors requested changes

2020-08-19 11:31 UTC, hors commented on e2e-tests/haproxy/run
> +    local haproxy_pod_ip=$(kubectl_bin describe pod $cluster-haproxy-$i | grep IP | head -n1 | awk '{print $2}')
```suggestion
    local haproxy_pod_ip=$(kubectl_bin get pods some-name-haproxy-0 -o jsonpath='{.status.podIP}') 
```

2020-08-19 11:44 UTC, cap1984 approved these changes

2020-08-19 11:48 UTC, hors approved these changes

2020-08-19 13:37 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| recreate | passed |
| init-deploy | passed |
| scaling | passed |
| storage | passed |
| self-healing | passed |
| limits | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| monitoring | passed |
| self-healing-advanced | passed |
| upgrade-consistency | passed |
| operator-self-healing | passed |
| security-context | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| scheduled-backup | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| haproxy | passed |
| demand-backup-encrypted-with-tls | failed |

2020-08-19 14:30 UTC, delgod requested changes

2020-08-19 14:30 UTC, delgod commented on e2e-tests/haproxy/conf/some-name.yml
> +apiVersion: pxc.percona.com/v1
please rename it to `haproxy` (similar to other tests)
reason: each unique configuration has its own name

2020-08-19 14:30 UTC, delgod commented on e2e-tests/haproxy/run
> +  kubectl_bin get svc some-name-proxysql
```suggestion
compare_kubectl statefulset/some-name-proxysql
compare_kubectl service/some-name-proxysql
```

2020-08-19 14:30 UTC, delgod commented on e2e-tests/haproxy/run
> +  kubectl_bin get svc some-name-haproxy
```suggestion
compare_kubectl service/some-name-haproxy
```

2020-08-19 14:30 UTC, delgod commented on e2e-tests/functions
> +    fi
please rebase this changes on brach from PR https://github.com/percona/percona-xtradb-cluster-operator/pull/524

2020-08-19 14:49 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| storage | passed |
| init-deploy | passed |
| big-data | passed |
| scaling | passed |
| scaling-proxysql | passed |
| limits | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| monitoring | passed |
| upgrade-consistency | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| self-healing-advanced | passed |
| affinity | passed |
| scheduled-backup | failed |
| one-pod | passed |
| auto-tuning | passed |
| operator-self-healing | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| haproxy | passed |
| demand-backup-encrypted-with-tls | failed |

2020-08-30 19:25 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| init-deploy | passed |
| big-data | passed |
| storage | passed |
| scaling | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| upgrade | passed |
| monitoring | passed |
| self-healing-advanced | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| scheduled-backup | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| haproxy | failed |

2020-08-30 19:27 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| recreate | passed |
| big-data | passed |
| scaling | passed |
| storage | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| limits | passed |
| monitoring | passed |
| upgrade | passed |
| restore-to-encrypted-cluster | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| upgrade-consistency | passed |
| security-context | passed |
| affinity | passed |
| demand-backup | passed |
| one-pod | passed |
| operator-self-healing | passed |
| auto-tuning | passed |
| scheduled-backup | failed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| haproxy | failed |

2020-08-31 04:44 UTC, delgod requested changes

2020-08-31 04:44 UTC, delgod commented on e2e-tests/functions
> +    fi
haproxy and servicename vars are not used, so we don't need this change anymore

2020-08-31 04:44 UTC, delgod commented on e2e-tests/haproxy/run
> +  compare_kubectl service/some-name-haproxy
minor improvement of style
```suggestion
  compare_kubectl statefulset/$cluster-proxysql
  compare_kubectl service/$cluster-proxysql

  desc 're-enable haproxy'
  apply_config "$test_dir/conf/$cluster.yml"
  sleep 50
  compare_kubectl statefulset/$cluster-haproxy
  compare_kubectl service/$cluster-haproxy
```

2020-08-31 04:44 UTC, delgod commented on e2e-tests/haproxy/conf/some-name.yml
> +      maxUnavailable: 1
minor improvement to test if it passed
```suggestion
      maxUnavailable: 2
```

2020-08-31 04:44 UTC, delgod commented on e2e-tests/haproxy/run
> +
can we also check podDisruptionBudget
```suggestion
    compare_kubectl pdb/$cluster-haproxy
```

2020-09-01 09:34 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |

2020-09-01 09:46 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |

2020-09-01 09:51 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |

2020-09-02 19:12 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |

2020-09-02 20:15 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scaling | failed |
| storage | passed |
| recreate | failed |
| haproxy | failed |
| big-data | passed |
| self-healing | failed |
| init-deploy | failed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| self-healing-advanced | passed |
| scaling-proxysql | failed |
| demand-backup | passed |
| monitoring | failed |
| operator-self-healing | passed |
| upgrade | passed |
| monitoring-2-0 | failed |
| upgrade-consistency | passed |
| scheduled-backup | failed |
| security-context | passed |
| affinity | passed |
| one-pod | passed |
| demand-backup-encrypted-with-tls | failed |
| auto-tuning | failed |
| proxysql-sidecar-res-limits | passed |
| users | failed |

2020-09-03 10:28 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |

2020-09-04 12:29 UTC, delgod approved these changes

2020-09-04 12:29 UTC, merged

2020-09-06 16:42 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| haproxy | passed |
| recreate | failed |
| scaling | failed |
| big-data | passed |
| init-deploy | failed |
| self-healing | failed |
| scaling-proxysql | failed |
| limits | passed |
| restore-to-encrypted-cluster | passed |
| monitoring | failed |
| self-healing-advanced | passed |
| upgrade | passed |
| demand-backup | passed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| upgrade-consistency | passed |
| security-context | passed |
| affinity | passed |
| one-pod | passed |
| scheduled-backup | failed |
| auto-tuning | failed |
| demand-backup-encrypted-with-tls | failed |
| proxysql-sidecar-res-limits | passed |
| users | failed |

2020-09-06 16:42 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| haproxy | passed |
| big-data | passed |
| recreate | failed |
| scaling | failed |
| self-healing | failed |
| init-deploy | failed |
| scaling-proxysql | failed |
| limits | passed |
| restore-to-encrypted-cluster | passed |
| monitoring | failed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| monitoring-2-0 | failed |
| demand-backup | passed |
| upgrade | passed |
| upgrade-consistency | passed |
| affinity | passed |
| security-context | passed |
| scheduled-backup | failed |
| one-pod | passed |
| auto-tuning | failed |
| demand-backup-encrypted-with-tls | failed |
| proxysql-sidecar-res-limits | passed |
| users | failed |

2020-09-06 16:42 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scaling | failed |
| recreate | failed |
| storage | passed |
| haproxy | failed |
| big-data | passed |
| self-healing | failed |
| init-deploy | failed |
| scaling-proxysql | failed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| monitoring | failed |
| demand-backup | passed |
| self-healing-advanced | passed |
| upgrade | passed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| upgrade-consistency | passed |
| security-context | passed |
| affinity | passed |
| scheduled-backup | failed |
| one-pod | passed |
| auto-tuning | failed |
| demand-backup-encrypted-with-tls | failed |
| proxysql-sidecar-res-limits | passed |
| users | failed |

2020-09-06 18:11 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| haproxy | failed |
| storage | passed |
| recreate | failed |
| scaling | failed |
| self-healing | failed |
| init-deploy | failed |
| restore-to-encrypted-cluster | passed |
| scaling-proxysql | failed |
| limits | passed |
| self-healing-advanced | passed |
| upgrade | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| monitoring | failed |
| upgrade-consistency | passed |
| security-context | passed |
| monitoring-2-0 | failed |
| scheduled-backup | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | failed |
| demand-backup-encrypted-with-tls | failed |
| proxysql-sidecar-res-limits | passed |
| users | failed |