K8SPXC-370 Fix 'scheduled-backup' test
percona/percona-xtradb-cluster-operator pull request #559
Opened 2020-09-11 13:27 UTC by hors

* fix 'scheduled-backup' test
    * add possibility to use 32 symbols for cluster name
    * start to use new helm repo for minio charts

2020-09-11 13:37 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |

2020-09-11 18:33 UTC, delgod requested changes

2020-09-11 18:33 UTC, delgod commented on pkg/pxc/backup/scheduled.go
> +									  name: "cron-${pxcCluster:0:16}-$(date -u "+%Y%m%d%H%M%S")-` + spec.StorageName + `-${suffix}"
should we limit the storage name to 16 chars?

2020-09-11 18:48 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| recreate | passed |
| scaling | passed |
| big-data | passed |
| storage | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | failed |
| upgrade | passed |
| self-healing-advanced | passed |
| limits | passed |
| upgrade-consistency | passed |
| security-context | failed |
| operator-self-healing | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | failed |
| demand-backup | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| scheduled-backup | failed |

2020-09-11 22:37 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| big-data | passed |
| haproxy | passed |
| storage | passed |
| scaling | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| limits | passed |
| upgrade-consistency | passed |
| self-healing-advanced | failed |
| security-context | passed |
| monitoring | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| scheduled-backup | failed |
| one-pod | passed |
| auto-tuning | passed |
| operator-self-healing | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |

2020-09-12 07:25 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| scaling | passed |
| scheduled-backup | failed |
| scaling-proxysql | passed |
| upgrade | passed |
| upgrade-consistency | passed |
| security-context | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| big-data | passed |
| operator-self-healing | passed |

2020-09-12 09:49 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| haproxy | passed |
| storage | passed |
| recreate | passed |
| scaling | passed |
| self-healing | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| limits | passed |
| self-healing-advanced | passed |
| upgrade-consistency | passed |
| monitoring | passed |
| security-context | passed |
| operator-self-healing | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| scheduled-backup | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |

2020-09-12 17:52 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| storage | passed |
| recreate | passed |
| scaling | passed |
| haproxy | passed |
| self-healing | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| limits | passed |
| self-healing-advanced | passed |
| upgrade-consistency | passed |
| monitoring | passed |
| security-context | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| operator-self-healing | passed |
| one-pod | passed |
| scheduled-backup | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | failed |

2020-09-12 22:00 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| storage | passed |
| recreate | passed |
| haproxy | passed |
| big-data | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| upgrade | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| self-healing-advanced | passed |
| upgrade-consistency | passed |
| security-context | passed |
| monitoring | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| affinity | passed |
| one-pod | passed |
| scheduled-backup | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | failed |

2020-09-12 22:06 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| big-data | passed |
| scaling | passed |
| haproxy | passed |
| recreate | passed |
| init-deploy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| limits | passed |
| self-healing-advanced | passed |
| upgrade-consistency | passed |
| monitoring | passed |
| security-context | passed |
| operator-self-healing | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| scheduled-backup | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | failed |

2020-09-13 08:06 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| haproxy | passed |
| demand-backup-encrypted-with-tls | failed |
| init-deploy | passed |
| limits | passed |
| big-data | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| scaling | passed |
| auto-tuning | passed |
| scaling-proxysql | passed |
| proxysql-sidecar-res-limits | passed |
| upgrade | passed |
| users | passed |
| upgrade-consistency | passed |
| security-context | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |

2020-09-14 07:21 UTC, delgod requested changes

2020-09-14 07:21 UTC, delgod commented on pkg/pxc/backup/scheduled.go
> +									  name: "cron-${pxcCluster:0:16}-$(date -u "+%Y%m%d%H%M%S")-` + trimNameRight(spec.StorageName, 16) + `-${suffix}"
```suggestion
									  name: "cron-${pxcCluster:0:16}-` + trimNameRight(spec.StorageName, 16) + `-$(date -u "+%Y%m%d%H%M%S")-${suffix}"
```

2020-09-14 12:00 UTC, hors commented on pkg/pxc/backup/scheduled.go
> +									  name: "cron-${pxcCluster:0:16}-$(date -u "+%Y%m%d%H%M%S")-` + trimNameRight(spec.StorageName, 16) + `-${suffix}"
done

2020-09-14 12:31 UTC, delgod approved these changes

2020-09-14 12:36 UTC, delgod approved these changes

2020-09-14 12:48 UTC, merged

2020-09-14 14:31 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| recreate | passed |
| haproxy | passed |
| big-data | passed |
| storage | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| self-healing | passed |
| upgrade | passed |
| restore-to-encrypted-cluster | failed |
| limits | passed |
| upgrade-consistency | passed |
| security-context | failed |
| monitoring | passed |
| demand-backup | failed |
| monitoring-2-0 | passed |
| self-healing-advanced | passed |
| affinity | passed |
| scheduled-backup | failed |
| one-pod | failed |
| operator-self-healing | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | failed |