K8SPXC-438 add possibility to use 32 symbols for cluster name
percona/percona-xtradb-cluster-operator pull request #560
Opened 2020-09-11 15:26 UTC by hors

2020-09-11 18:27 UTC, delgod requested changes

2020-09-11 18:27 UTC, delgod commented on Jenkinsfile
> +        IMAGE_BACKUP = 'perconalab/percona-xtradb-cluster-operator:master-pxc8.0-backup-test'
should we exclude this line from PR?

2020-09-12 05:32 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| big-data | passed |
| recreate | passed |
| scaling | passed |
| haproxy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| limits | passed |
| self-healing-advanced | passed |
| upgrade-consistency | passed |
| security-context | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| affinity | passed |
| operator-self-healing | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| scheduled-backup | failed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | failed |

2020-09-12 06:39 UTC, hors commented on Jenkinsfile
> +        IMAGE_BACKUP = 'perconalab/percona-xtradb-cluster-operator:master-pxc8.0-backup-test'
it was for tests

2020-09-12 09:48 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| scaling | passed |
| haproxy | passed |
| big-data | passed |
| storage | passed |
| init-deploy | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | failed |
| scaling-proxysql | passed |
| limits | passed |
| upgrade | passed |
| self-healing-advanced | passed |
| demand-backup | failed |
| monitoring | passed |
| upgrade-consistency | passed |
| operator-self-healing | passed |
| security-context | failed |
| scheduled-backup | failed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | failed |

2020-09-14 07:11 UTC, delgod approved these changes

2020-09-14 09:07 UTC, merged