K8SPXC-336 : refactor pxc status
percona/percona-xtradb-cluster-operator pull request #563
Opened 2020-09-12 22:25 UTC by AlyHKafoury

2020-09-13 01:37 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| haproxy | failed |
| storage | passed |
| recreate | passed |
| big-data | passed |
| scaling | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| self-healing-advanced | passed |
| limits | passed |
| upgrade-consistency | passed |
| security-context | passed |
| operator-self-healing | passed |
| demand-backup | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| scheduled-backup | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | failed |

2020-09-13 02:04 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| storage | passed |
| big-data | passed |
| haproxy | failed |
| recreate | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| upgrade | passed |
| restore-to-encrypted-cluster | passed |
| self-healing-advanced | passed |
| limits | passed |
| upgrade-consistency | passed |
| security-context | passed |
| operator-self-healing | passed |
| demand-backup | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| scheduled-backup | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | passed |

2020-09-16 14:37 UTC, hors requested changes
@AlyHKafoury  Did you cover all points from task https://jira.percona.com/browse/K8SPXC-336 in this  review ? e.g. what about points 1, 2 and 4. I do not see changes connected with these requirements.

2020-09-21 15:29 UTC, dAdAbird requested changes
See comments. 
Plus:
1. As @hors mentioned, there is nothing on p. 1 , 2 & 4.
2. There a lot of moving parts and we're constantly bumping into bugs here so I'd like to see unit tests for statuses.

2020-09-21 15:29 UTC, dAdAbird commented on pkg/controller/pxc/status.go
> +	case clusterStatus.ClusterInit():
Here (in [L238](https://github.com/percona/percona-xtradb-cluster-operator/pull/563/files#diff-b246f9cb3cd35db1c2d9931e00d89aabR238)) the AppStateInit being set and then later in [L259](https://github.com/percona/percona-xtradb-cluster-operator/pull/563/files#diff-b246f9cb3cd35db1c2d9931e00d89aabR259) basically a duplication. And for that duplication, we're maintaining "inProgres" variable a doing quite a bit extra stuff. I believe setting the AppStateInit here in sewitch-case is enough

2020-09-21 15:29 UTC, dAdAbird commented on pkg/controller/pxc/status.go
> +	if err := r.updateHAProxyStatus(cr, &inProgres, &clusterStatus); err != nil {
I don't quite like an idea that communication is built around changing the parameters passed to the method.
Now, these methods do a bit chaotic meaning that the do a lot of different stuff. Plus these set a lot of states. It's too unclear.

2020-12-29 07:27 UTC, delgod commented
will be reopened when finished

2020-12-29 07:27 UTC, closed without merging