K8SPXC-394 document cluster wide operation
percona/percona-xtradb-cluster-operator pull request #566
Opened 2020-09-14 07:07 UTC by fiowro

2020-09-18 12:11 UTC, hors requested changes

2020-09-18 12:11 UTC, hors commented on source/cluster-wide.rst
> +      $ kubectl get pods
```suggestion
      $ kubectl get pods -n pxc
```

2020-09-18 12:11 UTC, hors commented on source/cluster-wide.rst
> +      percona-xtradb-cluster-operator-dc67778fd-qtspz   1/1     Running   0          6m
```suggestion
```

2020-09-22 11:13 UTC, hors requested changes

2020-09-22 11:13 UTC, hors commented on source/cluster-wide.rst
> +By default, Percona XtraDB Cluster Operator functions in a specific Kubernetes
We need to add recommendation that we suggest using one  operator per  namespace but if you need you can use cluster-wide....

2020-09-28 14:19 UTC, hors approved these changes

2020-09-30 06:21 UTC, delgod approved these changes

2020-09-30 06:21 UTC, merged