K8SPXC-435 Do not show any passwords in log
percona/percona-xtradb-cluster-operator pull request #579
Opened 2020-09-20 16:15 UTC by hors

2020-09-20 19:18 UTC, JNKPercona commented
PXC operator docker - perconalab/percona-xtradb-cluster-operator:PR-579-dec6b148

2020-09-20 19:18 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| recreate | passed |
| storage | passed |
| big-data | passed |
| haproxy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| upgrade | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring | passed |
| upgrade-consistency | passed |
| security-context | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| scheduled-backup | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |

2020-09-21 04:27 UTC, delgod requested changes

2020-09-21 04:27 UTC, delgod commented on build/pxc-entrypoint.sh
> +		set -x
logging become enabled back only if condition is true

2020-09-21 04:27 UTC, delgod commented on build/pxc-entrypoint.sh
> +		set -x
the same

2020-09-21 04:27 UTC, delgod commented on build/pxc-entrypoint.sh
> +		set -x
the same

2020-09-21 04:27 UTC, delgod commented on build/pxc-entrypoint.sh
> +		set -x
the same

2020-09-21 06:43 UTC, delgod approved these changes

2020-09-21 06:44 UTC, merged