K8SPXC-456: trim "/versions" in versionservice url
percona/percona-xtradb-cluster-operator pull request #588
Opened 2020-09-22 17:16 UTC by qJkee

2020-09-22 19:35 UTC, tplavcic reviewed
The only complaint that I can find to this is that we maybe want to remove the ending `/` also, so if somebody has `https://check.percona.com/versions/` that it removes `/versions/`.
I know we didn't have this ending `/` in PXC cr.yaml example, but we have it in PSMDB: https://github.com/percona/percona-server-mongodb-operator/blob/master/deploy/cr.yaml#L16
Otherwise looks ok.

2020-09-22 22:45 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| haproxy | passed |
| big-data | passed |
| storage | failed |
| scaling | passed |
| scaling-proxysql | failed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| monitoring | failed |
| demand-backup | passed |
| self-healing | passed |
| scheduled-backup | passed |
| upgrade | passed |
| self-healing-advanced | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | failed |
| security-context | passed |
| demand-backup-encrypted-with-tls | passed |
| operator-self-healing | passed |
| affinity | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |

2020-09-23 06:49 UTC, delgod approved these changes

2020-09-23 06:50 UTC, delgod requested changes

2020-09-23 06:50 UTC, delgod commented on pkg/controller/pxc/vs.go
> +		BasePath: strings.TrimSuffix(requestURL.Path,"/versions"),
```suggestion
		BasePath: strings.TrimSuffix(strings.TrimSuffix(requestURL.Path,"/"),"/versions"),
```

2020-09-23 07:04 UTC, qJkee commented
> The only complaint that I can find to this is that we maybe want to remove the ending `/` also, so if somebody has `https://check.percona.com/versions/` that it removes `/versions/`.
> I know we didn't have this ending `/` in PXC cr.yaml example, but we have it in PSMDB: https://github.com/percona/percona-server-mongodb-operator/blob/master/deploy/cr.yaml#L16
> Otherwise looks ok.

Yea, it's exists in psmdb, but because we don't change it when it was updated
But while we have one and only one VS URL, we should not do any extra manipulations, which can cause bad effect in future with custom user's URL

2020-09-23 08:04 UTC, delgod requested changes

2020-09-23 08:04 UTC, delgod commented on pkg/controller/pxc/vs.go
```suggestion
if requestURL.Path == "https://check.percona.com/versions" {
    requestURL.Path = "https://check.percona.com"
}
```

2020-09-23 14:45 UTC, delgod requested changes

2020-09-23 14:45 UTC, delgod commented on deploy/cr.yaml
> +    versionServiceEndpoint: https://check.percona.com/versions
lets have correct value in the CR
```suggestion
    versionServiceEndpoint: https://check.percona.com
```

2020-09-23 14:58 UTC, delgod approved these changes

2020-09-23 15:42 UTC, tplavcic approved these changes

2020-09-23 15:47 UTC, merged

2020-09-23 19:34 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| big-data | passed |
| recreate | passed |
| haproxy | passed |
| storage | failed |
| scaling-proxysql | failed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| monitoring | failed |
| demand-backup | passed |
| self-healing | passed |
| upgrade | passed |
| scheduled-backup | passed |
| upgrade-consistency | passed |
| security-context | passed |
| monitoring-2-0 | failed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| demand-backup-encrypted-with-tls | failed |
| affinity | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |

2020-09-23 19:59 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| haproxy | passed |
| recreate | passed |
| big-data | passed |
| storage | failed |
| scaling-proxysql | failed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| monitoring | failed |
| demand-backup | passed |
| self-healing | passed |
| upgrade | passed |
| self-healing-advanced | passed |
| upgrade-consistency | passed |
| scheduled-backup | passed |
| security-context | passed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| demand-backup-encrypted-with-tls | failed |
| affinity | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |