K8SPXC-457: fix monitoring tests
percona/percona-xtradb-cluster-operator pull request #591
Opened 2020-09-23 07:00 UTC by qJkee

Test are falling because they can't find required secrets

2020-09-23 07:10 UTC, delgod requested changes

2020-09-23 07:10 UTC, delgod commented on e2e-tests/monitoring-2-0/conf/monitoring.yml
> +  sslInternalSecretName: some-name-ssl-internal
the internal secret is optional. please don't add it

2020-09-23 07:10 UTC, delgod commented on e2e-tests/monitoring/conf/monitoring.yml
> +  sslInternalSecretName: some-name-ssl-internal
the internal secret is optional. please don't add it

2020-09-23 10:41 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| big-data | passed |
| recreate | passed |
| haproxy | passed |
| scaling | passed |
| init-deploy | passed |
| scaling-proxysql | failed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| affinity | failed |
| self-healing | passed |
| scheduled-backup | passed |
| upgrade | passed |
| upgrade-consistency | passed |
| security-context | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| one-pod | passed |
| demand-backup-encrypted-with-tls | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |

2020-09-23 15:58 UTC, delgod approved these changes

2020-09-23 18:25 UTC, JNKPercona commented
PXC operator docker - perconalab/percona-xtradb-cluster-operator:PR-591-5050fcd1

2020-09-23 18:26 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| recreate | passed |
| storage | passed |
| haproxy | passed |
| scaling | passed |
| init-deploy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring | passed |
| upgrade-consistency | passed |
| security-context | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| scheduled-backup | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |

2020-09-23 18:33 UTC, hors approved these changes

2020-09-24 07:27 UTC, blez approved these changes

2020-09-24 07:30 UTC, merged