pK8SPXC-462 add readiness probe for HAproxy
percona/percona-xtradb-cluster-operator pull request #596
Opened 2020-09-24 13:47 UTC by hors

2020-09-24 17:03 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| scaling | passed |
| recreate | passed |
| big-data | passed |
| storage | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| limits | passed |
| self-healing-advanced | passed |
| upgrade-consistency | passed |
| monitoring | passed |
| security-context | passed |
| monitoring-2-0 | failed |
| demand-backup | passed |
| operator-self-healing | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| scheduled-backup | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-cert-manager-ref | passed |

2020-09-24 18:32 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |

2020-09-25 05:10 UTC, delgod requested changes

2020-09-25 05:10 UTC, delgod commented on pkg/pxc/app/statefulset/haproxy.go
> +		}, "/usr/local/bin/readiness-check.sh"),
why it is needed in the side car?

2020-09-25 05:10 UTC, delgod commented on pkg/pxc/app/statefulset/haproxy.go
> +			FailureThreshold:    5,
```suggestion
			FailureThreshold:    3,
```
what do you think?

2020-09-25 07:46 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| haproxy | passed |
| storage | passed |
| recreate | passed |
| big-data | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring | failed |
| upgrade-consistency | passed |
| demand-backup | passed |
| security-context | passed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| scheduled-backup | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager-ref | passed |

2020-09-25 10:17 UTC, hors commented on pkg/pxc/app/statefulset/haproxy.go
> +		}, "/usr/local/bin/readiness-check.sh"),
I have deleted it

2020-09-25 10:17 UTC, hors commented on pkg/pxc/app/statefulset/haproxy.go
> +			FailureThreshold:    5,
I think it is ok.

2020-09-25 11:50 UTC, delgod submitted a review, later dismissed

2020-09-25 13:27 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| big-data | passed |
| scaling | passed |
| haproxy | passed |
| recreate | passed |
| scaling-proxysql | passed |
| self-healing | failed |
| init-deploy | passed |
| upgrade | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| upgrade-consistency | passed |
| monitoring | passed |
| security-context | passed |
| demand-backup | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| scheduled-backup | passed |
| proxysql-sidecar-res-limits | passed |
| operator-self-healing | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | passed |

2020-09-25 15:08 UTC, merged