K8SPXC-510 Use ENV variables for images
percona/percona-xtradb-cluster-operator pull request #652
Opened 2020-10-25 15:49 UTC by cap1984

2020-10-25 16:20 UTC, delgod requested changes

2020-10-25 16:20 UTC, delgod commented on pkg/apis/pxc/v1/pxc_types.go
> +			c.HAProxy.ImagePullPolicy = corev1.PullIfNotPresent
why we need to rewrite already set policy?

2020-10-25 16:20 UTC, delgod commented on pkg/apis/pxc/v1/pxc_types.go
> +			c.PXC.ImagePullPolicy = corev1.PullIfNotPresent
policy can be set via CR, I believe we don't need to change it here

2020-10-25 18:58 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| recreate | passed |
| haproxy | passed |
| smart-update | failed |
| scaling | passed |
| big-data | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| upgrade | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| monitoring | failed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| affinity | failed |
| one-pod | passed |
| auto-tuning | passed |
| scheduled-backup | failed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| demand-backup-encrypted-with-tls | passed |

2020-10-26 12:47 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| smart-update | failed |
| scaling | passed |
| haproxy | passed |
| storage | failed |
| recreate | passed |
| big-data | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| self-healing | passed |
| upgrade | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| upgrade-consistency | passed |
| monitoring | failed |
| self-healing-advanced | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| affinity | failed |
| one-pod | passed |
| auto-tuning | passed |
| scheduled-backup | failed |
| proxysql-sidecar-res-limits | passed |
| users | failed |

2020-10-26 21:43 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring | failed |
| big-data | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| scheduled-backup | failed |
| scaling | passed |
| scaling-proxysql | passed |
| upgrade | passed |
| upgrade-consistency | passed |
| security-context | passed |
| smart-update | failed |
| storage | failed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| monitoring-2-0 | passed |
| affinity | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| demand-backup-encrypted-with-tls | failed |

2020-10-27 12:13 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| scaling | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| limits | passed |
| upgrade | passed |
| monitoring | failed |
| upgrade-consistency | passed |
| security-context | passed |
| big-data | passed |
| storage | failed |
| smart-update | failed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| scheduled-backup | failed |
| monitoring-2-0 | passed |
| affinity | failed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |

2020-11-04 17:14 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| smart-update | failed |
| haproxy | passed |
| storage | passed |
| recreate | passed |
| big-data | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| upgrade | failed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| operator-self-healing | failed |
| affinity | passed |
| demand-backup | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| scheduled-backup | passed |
| demand-backup-encrypted-with-tls | passed |

2020-11-04 20:25 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-encrypted-with-tls | passed |
| haproxy | passed |
| storage | passed |
| init-deploy | passed |
| self-healing | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring | passed |
| big-data | passed |
| operator-self-healing | failed |
| monitoring-2-0 | passed |
| scaling | passed |
| affinity | passed |
| scaling-proxysql | passed |
| one-pod | passed |
| upgrade | failed |
| smart-update | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |

2020-11-04 22:39 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| smart-update | failed |
| recreate | passed |
| scaling | passed |
| storage | passed |
| haproxy | passed |
| big-data | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| upgrade | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| self-healing-advanced | passed |
| upgrade-consistency | passed |
| monitoring | passed |
| operator-self-healing | failed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| security-context | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| scheduled-backup | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| demand-backup-encrypted-with-tls | failed |

2020-11-05 14:24 UTC, delgod approved these changes

2020-11-05 15:33 UTC, hors approved these changes

2020-11-05 15:57 UTC, merged