K8 spxc 485 document log collector
percona/percona-xtradb-cluster-operator pull request #716
Opened 2021-01-11 13:30 UTC by fiowro

2021-01-11 13:41 UTC, hors requested changes

2021-01-11 13:41 UTC, hors commented on source/debug.rst
> +   kubectl logs -c pxc-logcollector
```suggestion
   kubectl logs cluster1-pxc-1 -c logs
```

2021-01-11 13:41 UTC, hors commented on source/debug.rst
> +Cluster-level logging involves collecting logs from all components of the
For now we use it only for pxc pods and we use the same PVC as for pxc pod. The logs can be found in DATADIR /(var/lib/mysql/)

2021-01-18 09:18 UTC, hors submitted a review, later dismissed

2021-01-19 09:01 UTC, spron-in approved these changes

2021-01-19 18:12 UTC, merged