K8SPXC-622 add contributing guide
percona/percona-xtradb-cluster-operator pull request #782
Opened 2021-02-18 23:45 UTC by fiowro

2021-02-19 03:02 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| big-data | passed |
| scaling | passed |
| recreate | passed |
| haproxy | passed |
| upgrade-haproxy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| init-deploy | passed |
| self-healing-advanced | passed |
| demand-backup | passed |
| smart-update | passed |
| limits | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| affinity | passed |
| one-pod | passed |
| pitr | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | failed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-consistency | passed |
| users | passed |
| tls-issue-self | passed |
| scheduled-backup | failed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

2021-02-22 07:36 UTC, spron-in submitted a review, later dismissed

2021-02-22 15:37 UTC, delgod approved these changes

2021-02-22 16:08 UTC, spron-in requested changes

2021-02-22 16:08 UTC, spron-in commented on CONTRIBUTING.md
> +
```suggestion
Improvement and bugfix tasks for the Operator are tracked in [Jira](https://Jira.percona.com/projects/K8SPXC/issues), Although not mandatory, it is a good practice to examine already open Jira issues before submitting a pull request. For bigger contributions, we suggest creating a Jira issue first and discussing it with the engineering team and community before proposing any code changes. 

Another good place to discuss Percona Kubernetes Operator for Percona XtraDB Cluster with developers and other community members is the [community forum](https://forums.percona.com/categories/kubernetes-operator-percona-xtradb-cluster). 
```

2021-02-22 16:12 UTC, spron-in approved these changes

2021-02-22 16:18 UTC, delgod approved these changes

2021-02-22 16:18 UTC, merged

2021-02-22 18:53 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| haproxy | passed |
| upgrade-haproxy | passed |
| big-data | passed |
| recreate | passed |
| scaling | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| security-context | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| self-healing-advanced | passed |
| upgrade-proxysql | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| operator-self-healing | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | passed |
| demand-backup-encrypted-with-tls | failed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| scheduled-backup | failed |

2021-02-22 19:55 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| upgrade-haproxy | passed |
| big-data | passed |
| haproxy | passed |
| recreate | passed |
| scaling | passed |
| init-deploy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| monitoring-2-0 | passed |
| self-healing-advanced | passed |
| demand-backup | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| operator-self-healing | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | passed |
| demand-backup-encrypted-with-tls | passed |
| smart-update | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| scheduled-backup | failed |
| upgrade-consistency | passed |