Include namespace in auto recovery command
percona/percona-xtradb-cluster-operator pull request #864
Opened 2021-05-01 02:32 UTC by ExiaSR

Make our life easier to run the `kubectl exec` command when recovering manually.

2021-05-01 02:32 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster-operator?pullRequest=864) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster-operator?pullRequest=864) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtradb-cluster-operator?pullRequest=864) it.</sub>

2021-05-01 05:45 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| scheduled-backup | passed |
| storage | failed |
| upgrade-haproxy | failed |
| haproxy | passed |
| scaling | passed |
| big-data | passed |
| init-deploy | failed |
| scaling-proxysql | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| security-context | failed |
| limits | failed |
| upgrade-proxysql | failed |
| self-healing-advanced | passed |
| demand-backup | passed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| smart-update | passed |
| affinity | failed |
| one-pod | passed |
| pitr | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| demand-backup-encrypted-with-tls | passed |
| users | passed |
| upgrade-consistency | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/864/commits/ee34055225e15056998bf471be9846eff5c9dc6a
image: `perconalab/percona-xtradb-cluster-operator:PR-864-ee340552`

2021-05-03 07:42 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| haproxy | passed |
| demand-backup | passed |
| pitr | passed |
| init-deploy | failed |
| demand-backup-encrypted-with-tls | passed |
| big-data | passed |
| scheduled-backup | passed |
| storage | failed |
| scaling | passed |
| upgrade-haproxy | failed |
| scaling-proxysql | passed |
| security-context | failed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| limits | failed |
| monitoring-2-0 | failed |
| upgrade-proxysql | failed |
| affinity | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| smart-update | passed |
| upgrade-consistency | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/864/commits/ee34055225e15056998bf471be9846eff5c9dc6a
image: `perconalab/percona-xtradb-cluster-operator:PR-864-ee340552`

2021-05-03 10:51 UTC, qJkee approved these changes

2021-05-03 10:51 UTC, qJkee commented on pkg/pxc/app/statefulset/node.go
> +				Name: "MY_POD_NAMESPACE",
better to name it as `POD_NAMESPACE`

2021-05-03 10:52 UTC, qJkee requested changes

2021-05-03 10:52 UTC, qJkee commented on pkg/pxc/app/statefulset/node.go
> +				Name: "MY_POD_NAMESPACE",
better to name it as `POD_NAMESPACE`

2021-05-03 14:11 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/864/commits/a154cbd819b7e82c88e1eed5746fe4bcdcba546a
image: `perconalab/percona-xtradb-cluster-operator:PR-864-a154cbd8`

2021-05-04 06:21 UTC, qJkee submitted a review, later dismissed

2021-05-04 06:28 UTC, delgod requested changes

2021-05-04 06:28 UTC, delgod commented on pkg/pxc/app/statefulset/node.go
> +				ValueFrom: &corev1.EnvVarSource{
adding new vars adds unnecessary restarts of database during the update of the operator.
can you please take namespace from `/run/secrets/kubernetes.io/serviceaccount/namespace` file inside `build/pxc-entrypoint.sh` without adding any new env variables

2021-05-04 09:33 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| upgrade-haproxy | failed |
| recreate | passed |
| haproxy | passed |
| scheduled-backup | passed |
| big-data | passed |
| scaling | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| scaling-proxysql | passed |
| init-deploy | failed |
| upgrade-proxysql | failed |
| security-context | failed |
| self-healing-advanced | passed |
| demand-backup | passed |
| limits | failed |
| operator-self-healing | failed |
| monitoring-2-0 | failed |
| smart-update | passed |
| pitr | passed |
| affinity | failed |
| one-pod | passed |
| auto-tuning | passed |
| demand-backup-encrypted-with-tls | failed |
| proxysql-sidecar-res-limits | passed |
| upgrade-consistency | failed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/864/commits/a154cbd819b7e82c88e1eed5746fe4bcdcba546a
image: `perconalab/percona-xtradb-cluster-operator:PR-864-a154cbd8`

2021-05-04 18:05 UTC, delgod approved these changes

2021-05-04 18:30 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| scaling | passed |
| recreate | passed |
| upgrade-haproxy | passed |
| storage | passed |
| scheduled-backup | passed |
| haproxy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| init-deploy | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| limits | passed |
| monitoring-2-0 | failed |
| smart-update | passed |
| operator-self-healing | failed |
| restore-to-encrypted-cluster | passed |
| affinity | passed |
| one-pod | passed |
| demand-backup | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| upgrade-consistency | passed |
| users | failed |
| pitr | passed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-self | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/864/commits/a9da0d6b445b2156b62e8604c5400a7e4748a196
image: `perconalab/percona-xtradb-cluster-operator:PR-864-a9da0d6b`

2021-05-05 16:16 UTC, qJkee approved these changes

2021-05-05 17:53 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| scaling | passed |
| scaling-proxysql | passed |
| big-data | passed |
| security-context | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| scheduled-backup | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | failed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/864/commits/a9da0d6b445b2156b62e8604c5400a7e4748a196
image: `perconalab/percona-xtradb-cluster-operator:PR-864-a9da0d6b`

2021-05-07 07:43 UTC, merged