K8SPXC-720: add pitr test
percona/percona-xtradb-cluster-operator pull request #865
Opened 2021-05-03 10:27 UTC by qJkee

1. Add additional PITR test
2. Allow to set `timeBetweenUploads` as float value, instead of integer

2021-05-03 13:42 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| big-data | failed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| storage | passed |
| scaling | passed |
| recreate | passed |
| haproxy | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| self-healing | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| operator-self-healing | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | failed |
| users | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/865/commits/682c69ae465e2301c211d5756ff84b1ba4bdea51
image: `perconalab/percona-xtradb-cluster-operator:PR-865-682c69ae`

2021-05-04 07:13 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| scaling-proxysql | passed |
| affinity | passed |
| security-context | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| storage | passed |
| users | passed |
| self-healing | passed |
| tls-issue-self | passed |
| self-healing-advanced | passed |
| tls-issue-cert-manager | passed |
| operator-self-healing | passed |
| tls-issue-cert-manager-ref | passed |
| scheduled-backup | passed |
| validation-hook | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | failed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/865/commits/682c69ae465e2301c211d5756ff84b1ba4bdea51
image: `perconalab/percona-xtradb-cluster-operator:PR-865-682c69ae`

2021-05-04 11:58 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| scheduled-backup | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| recreate | passed |
| tls-issue-cert-manager | passed |
| restore-to-encrypted-cluster | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup | passed |
| validation-hook | passed |
| pitr | failed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/865/commits/682c69ae465e2301c211d5756ff84b1ba4bdea51
image: `perconalab/percona-xtradb-cluster-operator:PR-865-682c69ae`

2021-05-04 16:41 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| upgrade-haproxy | passed |
| big-data | passed |
| recreate | passed |
| storage | passed |
| scheduled-backup | passed |
| scaling | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| init-deploy | passed |
| self-healing-advanced | passed |
| limits | passed |
| demand-backup | passed |
| smart-update | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| affinity | passed |
| pitr | failed |
| one-pod | passed |
| auto-tuning | passed |
| upgrade-consistency | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/865/commits/23d0e757faada8f947cb987568fe4417dd27fd7e
image: `perconalab/percona-xtradb-cluster-operator:PR-865-23d0e757`

2021-05-05 08:03 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| storage | passed |
| self-healing | passed |
| scheduled-backup | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| haproxy | passed |
| init-deploy | passed |
| upgrade-haproxy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| big-data | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/865/commits/23d0e757faada8f947cb987568fe4417dd27fd7e
image: `perconalab/percona-xtradb-cluster-operator:PR-865-23d0e757`

2021-05-06 16:10 UTC, tplavcic approved these changes

2021-05-06 16:11 UTC, tplavcic commented
I see you gave up on sysbench 😄

2021-05-07 07:41 UTC, delgod requested changes

2021-05-07 07:41 UTC, delgod commented on e2e-tests/pitr/run
> +	run_recovery_check_pitr "$cluster" "restore-on-pitr-minio1" "on-pitr-minio1" "select-5" "" "$dest" ""
why we need similar check as in 109 line? can we add `run_backup ` and `write_more_data` before 108 line?

2021-05-07 08:05 UTC, delgod submitted a review, later dismissed

2021-05-07 09:24 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | passed |
| recreate | passed |
| storage | passed |
| haproxy | passed |
| big-data | passed |
| scaling | passed |
| upgrade-haproxy | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| affinity | passed |
| operator-self-healing | passed |
| one-pod | passed |
| smart-update | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | failed |
| users | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/865/commits/7f3c20756115b3e35773a1ee478f75437908414d
image: `perconalab/percona-xtradb-cluster-operator:PR-865-7f3c2075`

2021-05-07 12:11 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| scaling | passed |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| big-data | passed |
| recreate | passed |
| storage | passed |
| init-deploy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| limits | passed |
| self-healing-advanced | passed |
| upgrade-proxysql | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| affinity | passed |
| smart-update | passed |
| operator-self-healing | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| pitr | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| upgrade-consistency | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/865/commits/cdb35e2204a12b9e293fe4d11325ab686548292b
image: `perconalab/percona-xtradb-cluster-operator:PR-865-cdb35e22`

2021-05-07 18:15 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| haproxy | passed |
| upgrade-haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| storage | passed |
| affinity | passed |
| self-healing | passed |
| one-pod | passed |
| self-healing-advanced | passed |
| auto-tuning | passed |
| operator-self-healing | passed |
| proxysql-sidecar-res-limits | passed |
| scheduled-backup | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| big-data | passed |
| validation-hook | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | failed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/865/commits/cdb35e2204a12b9e293fe4d11325ab686548292b
image: `perconalab/percona-xtradb-cluster-operator:PR-865-cdb35e22`

2021-05-08 18:26 UTC, delgod approved these changes

2021-05-10 10:41 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| recreate | passed |
| proxysql-sidecar-res-limits | passed |
| restore-to-encrypted-cluster | passed |
| users | passed |
| demand-backup | passed |
| tls-issue-self | passed |
| pitr | failed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| big-data | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| scaling-proxysql | passed |
| scheduled-backup | passed |
| security-context | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/865/commits/cdb35e2204a12b9e293fe4d11325ab686548292b
image: `perconalab/percona-xtradb-cluster-operator:PR-865-cdb35e22`

2021-05-11 15:36 UTC, delgod approved these changes

2021-05-11 17:04 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| big-data | passed |
| storage | passed |
| haproxy | passed |
| scheduled-backup | passed |
| recreate | passed |
| upgrade-haproxy | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| self-healing | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| operator-self-healing | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/865/commits/aec14947cfa124836b7abbcc0d47c0c8848f1b66
image: `perconalab/percona-xtradb-cluster-operator:PR-865-aec14947`

2021-05-12 07:12 UTC, tplavcic submitted a review, later dismissed

2021-05-12 07:18 UTC, merged