K8SPXC-767: fix one pod test
percona/percona-xtradb-cluster-operator pull request #893
Opened 2021-06-04 10:52 UTC by qJkee

2021-06-04 13:56 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| big-data | passed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| self-healing | passed |
| upgrade-proxysql | passed |
| self-healing-chaos | passed |
| smart-update | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/893/commits/f04e57f8b1a5bc927c5cc99bdf5b937603023142
image: `perconalab/percona-xtradb-cluster-operator:PR-893-f04e57f8`

2021-06-07 09:22 UTC, hors requested changes
@qJkee please correct description of this commit, this commit fixes not only test :)

2021-06-07 10:48 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | passed |
| recreate | passed |
| big-data | passed |
| upgrade-haproxy | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scaling | passed |
| haproxy | passed |
| upgrade-proxysql | passed |
| scaling-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | passed |
| tls-issue-self | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/893/commits/f04e57f8b1a5bc927c5cc99bdf5b937603023142
image: `perconalab/percona-xtradb-cluster-operator:PR-893-f04e57f8`

2021-06-07 17:05 UTC, delgod approved these changes

2021-06-08 08:58 UTC, hors approved these changes

2021-06-08 08:58 UTC, merged