K8SPXC-569 update unsafe configuration option
percona/percona-xtradb-cluster-operator pull request #901
Opened 2021-06-11 09:10 UTC by fiowro

2021-06-11 09:31 UTC, delgod requested changes

2021-06-11 09:31 UTC, delgod commented on source/operator.rst
> +|                 | be more than 1 unless the ``spec.allowUnsafeConfigurations`` key is set to true.          |
```suggestion
|                 | be more than 2 unless the ``spec.allowUnsafeConfigurations`` key is set to true.          |
```

2021-06-11 09:31 UTC, delgod commented on source/operator.rst
>  | **Example**     | ``3``                                                                                     |
new default is `2`
```suggestion
| **Example**     | ``2``                                                                                     |
```

2021-06-11 09:31 UTC, delgod commented on source/operator.rst
> +|                 | should be more than 1 unless the ``spec.allowUnsafeConfigurations`` key is set to true.   |
```suggestion
|                 | should be more than 2 unless the ``spec.allowUnsafeConfigurations`` key is set to true.   |
```

2021-06-11 09:31 UTC, delgod commented on source/operator.rst
> +| **Example**     | ``3``                                                                                     |
new default is `2`
```suggestion
| **Example**     | ``2``                                                                                     |
```

2021-06-11 11:36 UTC, spron-in requested changes
Please fix the comments from Mykola

2021-06-11 14:50 UTC, delgod approved these changes

2021-07-13 08:46 UTC, spron-in requested changes

2021-07-13 08:46 UTC, spron-in commented on source/operator.rst
> +|                 | ``spec.allowUnsafeConfigurations`` key is set to true.                                    |
lets simplify this. We allow only 3 or 5 if unsafe is false.

2021-07-13 10:15 UTC, spron-in approved these changes

2021-07-14 11:14 UTC, merged