fix update and scale down concurrent
percona/percona-xtradb-cluster-operator pull request #909
Opened 2021-06-22 11:05 UTC by zlcnju

when the pxc sts is update and pxc size scale down concurrent, the operator will block until timeout because the pod will not restart in scaling down

2021-06-22 14:25 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| haproxy | passed |
| storage | passed |
| big-data | passed |
| scaling | passed |
| recreate | passed |
| scheduled-backup | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-chaos | passed |
| smart-update | passed |
| demand-backup | passed |
| limits | passed |
| monitoring-2-0 | passed |
| self-healing-advanced | passed |
| affinity | passed |
| one-pod | passed |
| self-healing-advanced-chaos | failed |
| auto-tuning | passed |
| operator-self-healing | passed |
| proxysql-sidecar-res-limits | failed |
| upgrade-consistency | passed |
| operator-self-healing-chaos | failed |
| pitr | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/909/commits/96a58a7579b66cc51138007616582ca985348e4c
image: `perconalab/percona-xtradb-cluster-operator:PR-909-96a58a75`

2021-06-23 06:14 UTC, zlcnju commented
@egegunes because lack of the permissions to jenkins, i cannot make effort to the failed test case.  Anything i can do?

2021-06-23 11:10 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| big-data | passed |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| recreate | passed |
| storage | passed |
| scaling | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-chaos | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| self-healing-advanced | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| self-healing-advanced-chaos | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | passed |
| validation-hook | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/909/commits/cdd5fee6f297b8e8beb87bd5aa4ffd8ddf1477b0
image: `perconalab/percona-xtradb-cluster-operator:PR-909-cdd5fee6`

2021-06-24 04:18 UTC, egegunes commented
@zlcnju thank you for your contribution. Tests seem OK but I want to check it manually

2021-06-24 04:18 UTC, egegunes requested changes

2021-06-24 04:18 UTC, egegunes commented on pkg/controller/pxc/upgrade.go
> +		return fmt.Errorf("compute pod order err, sfs name: %s, pod name: %s", sfs.Name, pod.Name)
please use `errors` package

2021-06-25 05:54 UTC, zlcnju commented on pkg/controller/pxc/upgrade.go
> +		return fmt.Errorf("compute pod order err, sfs name: %s, pod name: %s", sfs.Name, pod.Name)
fixed

2021-06-25 05:55 UTC, zlcnju commented on pkg/controller/pxc/upgrade.go
> +		return fmt.Errorf("compute pod order err, sfs name: %s, pod name: %s", sfs.Name, pod.Name)
> please use `errors` package

fixed

2021-06-25 09:18 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scheduled-backup | passed |
| storage | passed |
| big-data | passed |
| haproxy | passed |
| upgrade-haproxy | passed |
| recreate | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| init-deploy | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-chaos | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| self-healing-advanced | passed |
| smart-update | failed |
| affinity | passed |
| one-pod | passed |
| self-healing-advanced-chaos | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | failed |
| pitr | passed |
| operator-self-healing | passed |
| upgrade-consistency | passed |
| operator-self-healing-chaos | passed |
| users | failed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/909/commits/cf048fd6970e0ca1f9e84af5d33c12927cdccd5f
image: `perconalab/percona-xtradb-cluster-operator:PR-909-cf048fd6`

2021-06-25 13:21 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| recreate | passed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| haproxy | passed |
| storage | passed |
| init-deploy | passed |
| self-healing | passed |
| limits | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| self-healing-advanced-chaos | passed |
| affinity | passed |
| operator-self-healing | passed |
| one-pod | passed |
| operator-self-healing-chaos | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| upgrade-proxysql | passed |
| users | passed |
| smart-update | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/909/commits/cf048fd6970e0ca1f9e84af5d33c12927cdccd5f
image: `perconalab/percona-xtradb-cluster-operator:PR-909-cf048fd6`

2021-06-27 18:03 UTC, delgod approved these changes

2021-06-27 18:52 UTC, qJkee approved these changes

2021-06-28 07:30 UTC, egegunes approved these changes

2021-06-28 07:31 UTC, merged