K8SPXC-751 cross-site replication doc
percona/percona-xtradb-cluster-operator pull request #930
Opened 2021-07-12 15:26 UTC by fiowro

2021-07-19 08:21 UTC, qJkee commented on source/replication.rst
> +* ``spec.pxc.replicationChannels.[].sourcesList.[].weight`` is the *weight* of the source (``100`` by default).
remove spec =)

2021-07-19 08:22 UTC, qJkee commented on source/replication.rst
> +   Cluster node.
```suggestion
   Cluster pod.
```

2021-07-20 10:36 UTC, spron-in requested changes
I think we should move "Exposing instances of Percona XtraDB Cluster" under "Configuring cross-site replication on Source instances". It is how the user is going to read and configure - first configure the replication channels on the Source and expose the Source pods as the next step.

2021-08-02 12:44 UTC, hors approved these changes

2021-08-02 13:04 UTC, qJkee submitted a review, later dismissed

2021-08-03 07:19 UTC, spron-in requested changes

2021-08-03 07:19 UTC, spron-in commented on source/replication.rst
> +.. note:: Cross-site replication is based on `Automatic Asynchronous Replication Connection Failover<https://dev.mysql.com/doc/refman/8.0/en/replication-asynchronous-connection-failover.html>`_. Ther
```suggestion
.. note:: Cross-site replication is based on `Automatic Asynchronous Replication Connection Failover<https://dev.mysql.com/doc/refman/8.0/en/replication-asynchronous-connection-failover.html>`_. Therefore it requires  MySQL 8.0.22+ (Percona XtraDB Cluster 8.0.22+) to work.
```

2021-08-03 07:19 UTC, spron-in commented on source/replication.rst
> +The Operator automates configuration of *Source* and *Replica* Percona XtraDB Clusters, but the feature itself is not bound to Kubernetes. Either *Source* or *Replica* can run outside of Kubernetes a
```suggestion
The Operator automates configuration of *Source* and *Replica* Percona XtraDB Clusters, but the feature itself is not bound to Kubernetes. Either *Source* or *Replica* can run outside of Kubernetes, be regular MySQL and be out of the Operators’ control. 
```

2021-08-03 07:19 UTC, spron-in commented on source/replication.rst
> +The Operator automates configuration of *Source* and *Replica* Percona XtraDB Clusters, but the feature itself is not bound to Kubernetes. Either *Source* or *Replica* can run outside of Kubernetes a
I believe it is important to mention that this feature can work for regular MySQL as well, not only PXC.

2021-08-03 07:19 UTC, spron-in commented on source/replication.rst
> +Setting up Percona XtraDB Cluster for asynchronous replication without the Operator is described `here <https://www.percona.com/blog/2018/03/19/percona-xtradb-cluster-mysql-asynchronous-replication-a
This is quite an old blog post. Shall we use this one: https://www.percona.com/blog/2021/04/14/what-you-can-do-with-auto-failover-and-percona-distribution-for-mysql-8-0-x/ instead?

2021-08-05 07:02 UTC, qJkee approved these changes

2021-08-05 07:06 UTC, spron-in commented on source/replication.rst
> +           networking.gke.io/load-balancer-type: "Internal"
we say below " Please take into account, that you will need this IP address to be external
   for cross-region replication in most cases."

why do we have internal load balancer in the example? :)

2021-08-05 07:26 UTC, qJkee approved these changes

2021-08-05 11:26 UTC, spron-in approved these changes

2021-08-05 11:31 UTC, merged