K8SPXC-808 - Fix init-deploy and haproxy on kubernetes 1.21
percona/percona-xtradb-cluster-operator pull request #931
Opened 2021-07-13 13:17 UTC by tplavcic

2021-07-13 13:31 UTC, delgod submitted a review, later dismissed

2021-07-13 16:21 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| scaling | passed |
| storage | passed |
| upgrade-haproxy | passed |
| recreate | passed |
| big-data | passed |
| scheduled-backup | passed |
| scaling-proxysql | passed |
| self-healing | failed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| self-healing-chaos | failed |
| one-pod | passed |
| self-healing-advanced | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| self-healing-advanced-chaos | failed |
| users | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/931/commits/ddb8bbed3ed27d64f00141a0912978b3d4a17467
image: `perconalab/percona-xtradb-cluster-operator:PR-931-ddb8bbed`

2021-07-13 16:52 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| storage | passed |
| scaling | passed |
| haproxy | passed |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| recreate | passed |
| scaling-proxysql | passed |
| self-healing | failed |
| init-deploy | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| self-healing-chaos | failed |
| one-pod | passed |
| self-healing-advanced | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| self-healing-advanced-chaos | failed |
| users | failed |
| operator-self-healing | passed |
| upgrade-consistency | passed |
| operator-self-healing-chaos | failed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/931/commits/b807492067331199f314acc66e3fe0dd78f91a3c
image: `perconalab/percona-xtradb-cluster-operator:PR-931-b8074920`

2021-07-14 08:20 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| haproxy | passed |
| big-data | passed |
| upgrade-haproxy | passed |
| init-deploy | passed |
| scheduled-backup | passed |
| limits | passed |
| monitoring-2-0 | passed |
| storage | passed |
| affinity | passed |
| scaling | passed |
| self-healing | failed |
| one-pod | passed |
| scaling-proxysql | passed |
| auto-tuning | passed |
| security-context | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| self-healing-chaos | failed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/931/commits/b807492067331199f314acc66e3fe0dd78f91a3c
image: `perconalab/percona-xtradb-cluster-operator:PR-931-b8074920`

2021-07-14 11:03 UTC, hors requested changes
@tplavcic  please update 'compare' files for operator-self-healing tests

2021-07-14 12:29 UTC, hors approved these changes

2021-07-14 12:30 UTC, merged