K8SPXC-876: fix tests for EKS 1.21
percona/percona-xtradb-cluster-operator pull request #998
Opened 2021-09-22 13:01 UTC by defbin

this will fix tests on EKS for previous operator version

2021-09-22 13:10 UTC, delgod requested changes

2021-09-22 13:10 UTC, delgod commented on e2e-tests/functions
> +
can we add the change only `if k8s version >= 1.21 and platform is EKS` condition?

2021-09-22 13:14 UTC, cap1984 commented on e2e-tests/functions
> +	kpatch_set_field svc "${cluster}-pxc-unready" "/spec/publishNotReadyAddresses" true
It's better to detect the platform and operator version. Afterwards we will be able to make such an action

2021-09-22 13:18 UTC, hors requested changes

2021-09-22 13:18 UTC, hors commented on e2e-tests/functions
> +	kpatch_set_field svc "${cluster}-pxc-unready" "/spec/publishNotReadyAddresses" true
@defbin we have discussed it. You need to add  condition for it. Because we can run the tests on different version of k8s.

2021-09-22 16:15 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| big-data | passed |
| haproxy | failed |
| recreate | passed |
| scaling | passed |
| storage | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| init-deploy | passed |
| demand-backup | passed |
| smart-update | passed |
| limits | passed |
| self-healing-chaos | passed |
| monitoring-2-0 | passed |
| self-healing-advanced | passed |
| pitr | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| self-healing-advanced-chaos | passed |
| upgrade-consistency | passed |
| proxysql-sidecar-res-limits | passed |
| demand-backup-encrypted-with-tls | passed |
| operator-self-healing | failed |
| users | passed |
| tls-issue-self | passed |
| operator-self-healing-chaos | failed |
| tls-issue-cert-manager | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/998/commits/46f720c4082f5cf16b28a911d74ba0efb335a4a3
image: `perconalab/percona-xtradb-cluster-operator:PR-998-46f720c4`

2021-09-22 18:01 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| storage | passed |
| big-data | passed |
| recreate | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| self-healing-chaos | passed |
| demand-backup | passed |
| self-healing-advanced | passed |
| smart-update | passed |
| self-healing-advanced-chaos | failed |
| pitr | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/998/commits/632946ec33e78b78f71df0b4f3221ad62fc55959
image: `perconalab/percona-xtradb-cluster-operator:PR-998-632946ec`

2021-09-23 07:17 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| storage | passed |
| big-data | passed |
| recreate | passed |
| scheduled-backup | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| self-healing-chaos | passed |
| demand-backup | passed |
| self-healing-advanced | passed |
| pitr | passed |
| self-healing-advanced-chaos | passed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-proxysql | passed |
| scaling-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| init-deploy | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| security-context | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/998/commits/632946ec33e78b78f71df0b4f3221ad62fc55959
image: `perconalab/percona-xtradb-cluster-operator:PR-998-632946ec`

2021-09-23 09:04 UTC, cap1984 approved these changes

2021-09-24 12:21 UTC, delgod approved these changes

2021-09-24 12:22 UTC, hors approved these changes

2021-09-24 12:27 UTC, merged